<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Are you sure you want to delete this item?' => '',
    'Assigns' => '',
    'Author ID' => '',
    'Body' => '',
    'Class Assets' => '',
    'Class Assets ID' => '',
    'Class Subject ID' => '',
    'Class Subjects' => '',
    'Create Assign' => '',
    'Create Class Assets' => '',
    'Create Class Subjects' => '',
    'Create Groups' => '',
    'Create Mtm' => '',
    'Create Subjects' => '',
    'Delete' => '',
    'End' => '',
    'Group ID' => '',
    'Groups' => '',
    'ID' => '',
    'Mtm ID' => '',
    'Mtms' => '',
    'Name' => '',
    'Reset' => '',
    'Save' => '',
    'Search' => '',
    'Start' => '',
    'Subject ID' => '',
    'Subjects' => '',
    'The requested page does not exist.' => '',
    'Title' => '',
    'Update' => '',
    'Update Assign: {nameAttribute}' => '',
    'Update Class Assets: {nameAttribute}' => '',
    'Update Class Subjects: {nameAttribute}' => '',
    'Update Groups: {nameAttribute}' => '',
    'Update Mtm: {nameAttribute}' => '',
    'Update Subjects: {nameAttribute}' => '',
    'User ID' => '',
];
